# Generated by Django 6.0.5 on 2026-08-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
